// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKAwEHr--xierg_xctKobVmfiq9Zyr85c',
    appId: '1:67315578864:web:598189dbc33fdcc60ccf35',
    messagingSenderId: '67315578864',
    projectId: 'projecthealth360-70bb2',
    authDomain: 'projecthealth360-70bb2.firebaseapp.com',
    storageBucket: 'projecthealth360-70bb2.firebasestorage.app',
    measurementId: 'G-Q7G08BP99S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGxl4sL_qFuIi0EFaaONzNUOWbzb5sG_E',
    appId: '1:67315578864:android:34b4c7d60501823d0ccf35',
    messagingSenderId: '67315578864',
    projectId: 'projecthealth360-70bb2',
    storageBucket: 'projecthealth360-70bb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtKUs7zUe85W8oLP9vumBGJE5TtvNL7K0',
    appId: '1:67315578864:ios:b3745fa19bd00d360ccf35',
    messagingSenderId: '67315578864',
    projectId: 'projecthealth360-70bb2',
    storageBucket: 'projecthealth360-70bb2.firebasestorage.app',
    iosBundleId: 'com.example.healthcareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtKUs7zUe85W8oLP9vumBGJE5TtvNL7K0',
    appId: '1:67315578864:ios:b3745fa19bd00d360ccf35',
    messagingSenderId: '67315578864',
    projectId: 'projecthealth360-70bb2',
    storageBucket: 'projecthealth360-70bb2.firebasestorage.app',
    iosBundleId: 'com.example.healthcareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKAwEHr--xierg_xctKobVmfiq9Zyr85c',
    appId: '1:67315578864:web:3b242b974317261b0ccf35',
    messagingSenderId: '67315578864',
    projectId: 'projecthealth360-70bb2',
    authDomain: 'projecthealth360-70bb2.firebaseapp.com',
    storageBucket: 'projecthealth360-70bb2.firebasestorage.app',
    measurementId: 'G-HWPYWPZ0SJ',
  );
}
