import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> addFakeDoctors() async {
  final doctorRef = FirebaseFirestore.instance.collection('doctors');

  List<Map<String, dynamic>> doctors = [
    {
      "fullName": "Dr. Arjun Reddy",
      "gender": "Male",
      "dateOfBirth": "1978-03-12",
      "profilePicture": "https://randomuser.me/api/portraits/men/1.jpg",
      "contactNumber": "+91-9876543210",
      "email": "arjun.reddy@example.com",
      "address": {"city": "Hyderabad", "state": "Telangana", "country": "India", "pincode": "500001"},
      "specialization": "Cardiologist",
      "qualifications": ["MBBS", "MD"],
      "experienceYears": 15,
      "languagesSpoken": ["English", "Hindi", "Telugu"],
      "licenseNumber": "MCI1001",
      "affiliatedHospital": ["Apollo Hospitals"],
      "consultationType": "both",
      "availableDays": ["Mon", "Wed", "Fri"],
      "availableSlots": ["10:00-13:00", "16:00-19:00"],
      "consultationFee": 800,
      "currency": "INR",
      "rating": 4.6,
      "reviewsCount": 95,
      "bio": "Experienced cardiologist with 15 years of practice.",
      "createdAt": FieldValue.serverTimestamp(),
      "updatedAt": FieldValue.serverTimestamp(),
      "isVerified": true
    },
    {
      "fullName": "Dr. Meera Nair",
      "gender": "Female",
      "dateOfBirth": "1985-07-25",
      "profilePicture": "https://randomuser.me/api/portraits/women/2.jpg",
      "contactNumber": "+91-9123456789",
      "email": "meera.nair@example.com",
      "address": {"city": "Kochi", "state": "Kerala", "country": "India", "pincode": "682001"},
      "specialization": "Dermatologist",
      "qualifications": ["MBBS", "DVD"],
      "experienceYears": 10,
      "languagesSpoken": ["English", "Malayalam", "Hindi"],
      "licenseNumber": "MCI1002",
      "affiliatedHospital": ["Amrita Institute of Medical Sciences"],
      "consultationType": "online",
      "availableDays": ["Tue", "Thu", "Sat"],
      "availableSlots": ["09:00-12:00", "14:00-17:00"],
      "consultationFee": 600,
      "currency": "INR",
      "rating": 4.8,
      "reviewsCount": 120,
      "bio": "Specialist in skin care and cosmetology with 10 years of experience.",
      "createdAt": FieldValue.serverTimestamp(),
      "updatedAt": FieldValue.serverTimestamp(),
      "isVerified": true
    },
    {
      "fullName": "Dr. Rahul Sharma",
      "gender": "Male",
      "dateOfBirth": "1982-01-08",
      "profilePicture": "https://randomuser.me/api/portraits/men/3.jpg",
      "contactNumber": "+91-9988776655",
      "email": "rahul.sharma@example.com",
      "address": {"city": "Delhi", "state": "Delhi", "country": "India", "pincode": "110001"},
      "specialization": "Orthopedic Surgeon",
      "qualifications": ["MBBS", "MS Ortho"],
      "experienceYears": 12,
      "languagesSpoken": ["English", "Hindi"],
      "licenseNumber": "MCI1003",
      "affiliatedHospital": ["AIIMS Delhi"],
      "consultationType": "offline",
      "availableDays": ["Mon", "Tue", "Thu"],
      "availableSlots": ["11:00-14:00", "17:00-20:00"],
      "consultationFee": 900,
      "currency": "INR",
      "rating": 4.5,
      "reviewsCount": 87,
      "bio": "Orthopedic surgeon with expertise in joint replacement.",
      "createdAt": FieldValue.serverTimestamp(),
      "updatedAt": FieldValue.serverTimestamp(),
      "isVerified": true
    },
    {
      "fullName": "Dr. Kavya Menon",
      "gender": "Female",
      "dateOfBirth": "1990-04-19",
      "profilePicture": "https://randomuser.me/api/portraits/women/4.jpg",
      "contactNumber": "+91-9765432100",
      "email": "kavya.menon@example.com",
      "address": {"city": "Bengaluru", "state": "Karnataka", "country": "India", "pincode": "560001"},
      "specialization": "Pediatrician",
      "qualifications": ["MBBS", "MD Pediatrics"],
      "experienceYears": 8,
      "languagesSpoken": ["English", "Kannada", "Hindi"],
      "licenseNumber": "MCI1004",
      "affiliatedHospital": ["Fortis Hospital"],
      "consultationType": "both",
      "availableDays": ["Wed", "Fri", "Sun"],
      "availableSlots": ["10:00-13:00", "15:00-18:00"],
      "consultationFee": 700,
      "currency": "INR",
      "rating": 4.9,
      "reviewsCount": 150,
      "bio": "Pediatrician passionate about child healthcare.",
      "createdAt": FieldValue.serverTimestamp(),
      "updatedAt": FieldValue.serverTimestamp(),
      "isVerified": true
    },
    {
      "fullName": "Dr. Suresh Bhat",
      "gender": "Male",
      "dateOfBirth": "1975-11-30",
      "profilePicture": "https://randomuser.me/api/portraits/men/5.jpg",
      "contactNumber": "+91-9812345678",
      "email": "suresh.bhat@example.com",
      "address": {"city": "Mumbai", "state": "Maharashtra", "country": "India", "pincode": "400001"},
      "specialization": "Neurologist",
      "qualifications": ["MBBS", "DM Neurology"],
      "experienceYears": 20,
      "languagesSpoken": ["English", "Hindi", "Marathi"],
      "licenseNumber": "MCI1005",
      "affiliatedHospital": ["Lilavati Hospital"],
      "consultationType": "offline",
      "availableDays": ["Mon", "Thu", "Sat"],
      "availableSlots": ["09:30-12:30", "18:00-20:00"],
      "consultationFee": 1200,
      "currency": "INR",
      "rating": 4.7,
      "reviewsCount": 210,
      "bio": "Neurologist with two decades of clinical experience.",
      "createdAt": FieldValue.serverTimestamp(),
      "updatedAt": FieldValue.serverTimestamp(),
      "isVerified": true
    },
    {
      "fullName": "Dr. Anjali Desai",
      "gender": "Female",
      "dateOfBirth": "1987-09-14",
      "profilePicture": "https://randomuser.me/api/portraits/women/6.jpg",
      "contactNumber": "+91-9345678901",
      "email": "anjali.desai@example.com",
      "address": {"city": "Ahmedabad", "state": "Gujarat", "country": "India", "pincode": "380001"},
      "specialization": "Gynecologist",
      "qualifications": ["MBBS", "MD Gynae"],
      "experienceYears": 11,
      "languagesSpoken": ["English", "Hindi", "Gujarati"],
      "licenseNumber": "MCI1006",
      "affiliatedHospital": ["Sterling Hospital"],
      "consultationType": "both",
      "availableDays": ["Tue", "Thu", "Sat"],
      "availableSlots": ["10:00-13:00", "17:00-20:00"],
      "consultationFee": 850,
      "currency": "INR",
      "rating": 4.9,
      "reviewsCount": 132,
      "bio": "Gynecologist with expertise in high-risk pregnancies.",
      "createdAt": FieldValue.serverTimestamp(),
      "updatedAt": FieldValue.serverTimestamp(),
      "isVerified": true
    },
    {
      "fullName": "Dr. Manoj Gupta",
      "gender": "Male",
      "dateOfBirth": "1981-06-02",
      "profilePicture": "https://randomuser.me/api/portraits/men/7.jpg",
      "contactNumber": "+91-9678901234",
      "email": "manoj.gupta@example.com",
      "address": {"city": "Jaipur", "state": "Rajasthan", "country": "India", "pincode": "302001"},
      "specialization": "Oncologist",
      "qualifications": ["MBBS", "DM Oncology"],
      "experienceYears": 14,
      "languagesSpoken": ["English", "Hindi"],
      "licenseNumber": "MCI1007",
      "affiliatedHospital": ["SMS Hospital"],
      "consultationType": "offline",
      "availableDays": ["Mon", "Wed", "Fri"],
      "availableSlots": ["09:00-12:00", "15:00-18:00"],
      "consultationFee": 1100,
      "currency": "INR",
      "rating": 4.8,
      "reviewsCount": 188,
      "bio": "Oncologist focusing on chemotherapy and cancer research.",
      "createdAt": FieldValue.serverTimestamp(),
      "updatedAt": FieldValue.serverTimestamp(),
      "isVerified": true
    },
    {
      "fullName": "Dr. Priya Sinha",
      "gender": "Female",
      "dateOfBirth": "1992-12-22",
      "profilePicture": "https://randomuser.me/api/portraits/women/8.jpg",
      "contactNumber": "+91-9012345678",
      "email": "priya.sinha@example.com",
      "address": {"city": "Patna", "state": "Bihar", "country": "India", "pincode": "800001"},
      "specialization": "Psychiatrist",
      "qualifications": ["MBBS", "MD Psychiatry"],
      "experienceYears": 6,
      "languagesSpoken": ["English", "Hindi"],
      "licenseNumber": "MCI1008",
      "affiliatedHospital": ["IGIMS Patna"],
      "consultationType": "online",
      "availableDays": ["Mon", "Wed", "Fri"],
      "availableSlots": ["10:00-12:00", "17:00-19:00"],
      "consultationFee": 650,
      "currency": "INR",
      "rating": 4.5,
      "reviewsCount": 70,
      "bio": "Young psychiatrist passionate about mental health awareness.",
      "createdAt": FieldValue.serverTimestamp(),
      "updatedAt": FieldValue.serverTimestamp(),
      "isVerified": false
    },
    {
      "fullName": "Dr. Vishal Kulkarni",
      "gender": "Male",
      "dateOfBirth": "1979-05-10",
      "profilePicture": "https://randomuser.me/api/portraits/men/9.jpg",
      "contactNumber": "+91-9543216789",
      "email": "vishal.kulkarni@example.com",
      "address": {"city": "Pune", "state": "Maharashtra", "country": "India", "pincode": "411001"},
      "specialization": "Urologist",
      "qualifications": ["MBBS", "MCh Urology"],
      "experienceYears": 16,
      "languagesSpoken": ["English", "Hindi", "Marathi"],
      "licenseNumber": "MCI1009",
      "affiliatedHospital": ["Ruby Hall Clinic"],
      "consultationType": "both",
      "availableDays": ["Tue", "Thu", "Sat"],
      "availableSlots": ["11:00-14:00", "18:00-21:00"],
      "consultationFee": 950,
      "currency": "INR",
      "rating": 4.7,
      "reviewsCount": 142,
      "bio": "Specialist in kidney and urinary tract disorders.",
      "createdAt": FieldValue.serverTimestamp(),
      "updatedAt": FieldValue.serverTimestamp(),
      "isVerified": true
    },
    // 🔽 add remaining doctors here up to 20...
  ];

  for (var doctor in doctors) {
    await doctorRef.add(doctor);
  }

  print("✅ 20 Fake doctors added successfully!");
}
